/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppScanRouteImport } from './routes/app.scan'
import { Route as AppAskRouteImport } from './routes/app.ask'
import { Route as AppAddRouteImport } from './routes/app.add'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppAddRoute = AppAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/add': typeof AppAddRoute
  '/app/ask': typeof AppAskRoute
  '/app/scan': typeof AppScanRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/add': typeof AppAddRoute
  '/app/ask': typeof AppAskRoute
  '/app/scan': typeof AppScanRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/add': typeof AppAddRoute
  '/app/ask': typeof AppAskRoute
  '/app/scan': typeof AppScanRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/add'
    | '/app/ask'
    | '/app/scan'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/app/add' | '/app/ask' | '/app/scan' | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/add'
    | '/app/ask'
    | '/app/scan'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ask': {
      id: '/app/ask'
      path: '/ask'
      fullPath: '/app/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/add': {
      id: '/app/add'
      path: '/add'
      fullPath: '/app/add'
      preLoaderRoute: typeof AppAddRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAddRoute: typeof AppAddRoute
  AppAskRoute: typeof AppAskRoute
  AppScanRoute: typeof AppScanRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddRoute: AppAddRoute,
  AppAskRoute: AppAskRoute,
  AppScanRoute: AppScanRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
